In [2]:
import pandas as pd
import re

In [3]:
sirenaExport = pd.read_csv('Sirena-export-fixed.csv', index_col='id')

In [3]:
boarding_data = pd.read_csv('BoardingData.csv', sep=';')

In [4]:
boarding_data

,PassengerFirstName,PassengerSecondName,PassengerLastName,PassengerSex,PassengerBirthDate,PassengerDocument,BookingCode,TicketNumber,Baggage,FlightDate,FlightTime,FlightNumber,CodeShare,Destination
0,SAVELII,VIKTOROVICH,RUSANOV,Male,03/10/1983,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05,SU1369,Own,Moscow
1,LEV,MARKOVICH,ISAEV,Male,12/13/1975,1788 173211,Not presented,1643715499224676,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
2,NIKOLAI,I.,NIKOLSKII,Male,12/26/1990,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10,SU1180,Own,Volgograd
3,ANATOLII,PETROVICH,SHILOV,Male,05/24/1997,2595 919752,WQFFUE,Not presented,Registered,2017-03-18,22:10,SU1180,Own,Volgograd
4,MIROSLAVA,VIACHESLAVOVNA,SEMENOVA,Female,01/31/1976,6775 516990,Not presented,Not presented,Registered,2017-03-12,11:45,SU6284,Own,Moscow
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155142,RAMIL,S.,DOROFEEV,Male,02/14/1994,3256 077151,SNRBXU,8653871661040452,Delayed,2017-05-18,06:30,SU1158,Own,Rostov
155143,RUSLAN,KONSTANTINOVICH,CHISTIAKOV,Male,02/14/1975,3497 458395,Not presented,0223584175158947,None,2017-05-18,06:30,SU1158,Own,Rostov
155144,SOFIA,VALEREVNA,KALMYKOVA,Female,12/17/1972,6618 352713,Not presented,Not presented,Registered,2017-10-02,07:30,SU5614,Own,Petropavlovsk
155145,VIACHESLAV,F.,KONONOV,Male,05/20/2000,4567 242088,Not presented,0975693658645383,Registered,2017-09-16,07:00,SU1640,Own,Omsk
155146,ESENIIA,DANILOVNA,BLINOVA,Female,03/07/1984,2861 762272,Not presented,Not presented,None,2017-05-09,07:00,SU1279,Own,Moscow

In [5]:
df = pd.DataFrame(boarding_data, columns=['PassengerFirstName', 'PassengerSecondName', 'PassengerLastName', 'PassengerBirthDate'])

In [6]:
boarding_data.value_counts('PassengerBirthDate')

PassengerBirthDate
10/27/1991    45
01/02/1976    45
06/20/1997    44
03/14/1979    44
06/15/1972    43
              ..
03/31/1984     1
01/18/2000     1
11/08/1998     1
11/08/1983     1
01/30/1991     1
Length: 11301, dtype: int64

In [7]:
info = df.duplicated(keep=False)

In [8]:
info

0         False
1          True
2          True
3          True
4          True
          ...
155142    False
155143     True
155144     True
155145    False
155146     True
Length: 155147, dtype: bool

In [9]:
count = 0
for i in info:
    if i:
        #print(boarding_data['PassengerFirstName'][count] + ' ' + 
         #     boarding_data['PassengerSecondName'][count] + ' ' + 
          #    boarding_data['PassengerLastName'][count] + ' ' + boarding_data['PassengerBirthDate'][count])
        count += 1
print(count)

91753

## Выделяем людей, летавших более одного раза

In [10]:
names = []

for i in range(len(boarding_data)):
    names.append(boarding_data['PassengerFirstName'][i] + ' ' + boarding_data['PassengerLastName'][i])
#pd.unique(boarding_data['PassengerFirstName'], boarding_data['PassengerSecondName'], boarding_data['PassengerLastName'])

In [11]:
name = pd.DataFrame(names)
dup = name.duplicated(keep='last')

In [12]:
index = 0
all_dup_names = []
for i in dup:
    if i:
        all_dup_names.append(names[index])
    index += 1

In [13]:
dup_names = list(dict.fromkeys(all_dup_names)) # все дубликаты

In [14]:
df = pd.DataFrame(dup_names, columns=['Name'])

In [16]:
df.to_csv('dup_names.csv', index=False)

In [17]:
boarding_data['Name'] = [boarding_data['PassengerFirstName'][i] + ' ' + 
                         boarding_data['PassengerLastName'][i] for i in range(len(boarding_data))]

In [99]:
boarding_data

,PassengerFirstName,PassengerSecondName,PassengerLastName,PassengerSex,PassengerBirthDate,PassengerDocument,BookingCode,TicketNumber,Baggage,FlightDate,FlightTime,FlightNumber,CodeShare,Destination,Name
0,SAVELII,VIKTOROVICH,RUSANOV,Male,03/10/1983,2879 096860,FRNINO,6625956945991971,Transit,2017-03-22,06:05,SU1369,Own,Moscow,SAVELII RUSANOV
1,LEV,MARKOVICH,ISAEV,Male,12/13/1975,1788 173211,Not presented,1643715499224676,Registered,2017-03-18,22:10,SU1180,Own,Volgograd,LEV ISAEV
2,NIKOLAI,I.,NIKOLSKII,Male,12/26/1990,4396 926588,VWNYGF,6247422701565929,Transit,2017-03-18,22:10,SU1180,Own,Volgograd,NIKOLAI NIKOLSKII
3,ANATOLII,PETROVICH,SHILOV,Male,05/24/1997,2595 919752,WQFFUE,Not presented,Registered,2017-03-18,22:10,SU1180,Own,Volgograd,ANATOLII SHILOV
4,MIROSLAVA,VIACHESLAVOVNA,SEMENOVA,Female,01/31/1976,6775 516990,Not presented,Not presented,Registered,2017-03-12,11:45,SU6284,Own,Moscow,MIROSLAVA SEMENOVA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155142,RAMIL,S.,DOROFEEV,Male,02/14/1994,3256 077151,SNRBXU,8653871661040452,Delayed,2017-05-18,06:30,SU1158,Own,Rostov,RAMIL DOROFEEV
155143,RUSLAN,KONSTANTINOVICH,CHISTIAKOV,Male,02/14/1975,3497 458395,Not presented,0223584175158947,None,2017-05-18,06:30,SU1158,Own,Rostov,RUSLAN CHISTIAKOV
155144,SOFIA,VALEREVNA,KALMYKOVA,Female,12/17/1972,6618 352713,Not presented,Not presented,Registered,2017-10-02,07:30,SU5614,Own,Petropavlovsk,SOFIA KALMYKOVA
155145,VIACHESLAV,F.,KONONOV,Male,05/20/2000,4567 242088,Not presented,0975693658645383,Registered,2017-09-16,07:00,SU1640,Own,Omsk,VIACHESLAV KONONOV
155146,ESENIIA,DANILOVNA,BLINOVA,Female,03/07/1984,2861 762272,Not presented,Not presented,None,2017-05-09,07:00,SU1279,Own,Moscow,ESENIIA BLINOVA

In [18]:
boarding_data.to_csv('boarding_data2.csv', index=False)

## Проверяем номера билетов

In [22]:
tickets = []
for i in range(len(boarding_data)):
    if boarding_data['TicketNumber'][i] != 'Not presented':
        tickets.append(boarding_data['TicketNumber'][i])

In [37]:
ticket = pd.DataFrame(tickets)
dup = ticket.duplicated(keep='last')

In [39]:
dup.sum()

0

In [35]:
sirenaExport

,PaxName,BirthDate,DepartDate,DepartTime,ArrivalDate,ArrivalTime,FlightCode,From,Dest,Ticket,TravelDoc,Seat,Meal,TravelClass,PaxAdditionalInfo,Loyalty,AgentInfo,Fare,Baggage
id,,,,,,,,,,,,,,,,,,,
0,ОЗЕРОВ ИЛЬДАР ДАНИИЛОВИЧ,1999-05-15,2017-05-30,00:05,2017-05-30,08:05,SU1306NO,SVO,OVB,ZBQSPY7360415302044672,9375 053270,NaN,NaN,J,S,FF#SU 38116280,Go2See,JGRPGN,0PC
1,КОЛОСОВ САМИР ТАМЕРЛАНОВИЧ,NaN,2017-12-27,02:15,2017-12-27,04:40,SU1323NO,MMK,SVO,MHPBBX7398421117936516,2244 645520,NaN,KSML,Y,9,FF#FB 284903754,NaN,YRSTUQ,NaN
2,ИГНАТОВА СНЕЖАНА КОНСТАНТИНОВНА,NaN,2017-09-19,06:40,2017-09-19,07:45,SU1481NO,KJA,SVO,REDLVB5174973140468001,8115 961316,NaN,NaN,Y,F,NaN,KupiBilet,YSTNJL,NaN
3,ЖАРОВ ПЛАТОН АЛЬБЕРТОВИЧ,1999-05-02,2017-03-18,22:10,2017-03-19,01:05,SU1180NO,SVO,VOG,NSJNGQ5274206497242737,98 6865148,NaN,NaN,J,#,FF#FB 884556993,Travelgenio,JFLXLS,0PC
4,НИКОЛЬСКИЙ НИКОЛАЙ ИГОРЕВИЧ,1990-12-26,2017-03-18,22:10,2017-03-19,01:05,SU1180NO,SVO,VOG,VWNYGF6247422701565929,4396 926588,NaN,NaN,Y,NaN,FF#SU 183142068,OZON.travel,YFLXPG,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155752,ЕМЕЛЬЯНОВ МИРОСЛАВ СВЯТОСЛАВОВИЧ,NaN,2017-02-14,03:10,2017-02-14,04:00,SU1181NO,VOG,SVO,JYYXED4714800502596692,3511 319326,NaN,STML,Y,F,NaN,OneTwoTrip,YSTNER,NaN
155753,ТАРАСОВ АРТЕМИЙ ГЕРМАНОВИЧ,NaN,2017-02-14,03:10,2017-02-14,04:00,SU1181NO,VOG,SVO,XDKDZF6730365623280343,2199 078129,NaN,NaN,Y,T,FF#DT 261604825,OZON.travel,YFLXKV,1PC
155754,ГОРОХОВ БОРИС СВЯТОГОРОВИЧ,1970-10-28,2017-02-14,03:10,2017-02-14,04:00,SU1181NO,VOG,SVO,SOWGLC1569746161308219,7351 760618,NaN,NaN,Y,F,FF#FB 902862806,Aeroflot,YFLXBF,NaN
155755,ДОРОФЕЕВ РАМИЛЬ СВЯТОСЛАВОВИЧ,1994-02-14,2017-05-18,06:30,2017-05-18,08:35,SU1158NO,SVO,ROV,SNRBXU8653871661040452,3256 077151,NaN,NaN,Y,#,NaN,NaN,YGRPMD,NaN
155756,ШАПОВАЛОВА ВАРВАРА ДАНИЛОВНА,NaN,2017-05-09,07:00,2017-05-09,08:35,SU1279NO,KZN,SVO,JMGRLT5113294821402227,8328 780960,NaN,NaN,Y,NaN,FF#DT 520710243,Aerobilet,YSTNKV,NaN

In [40]:
sirenaExport.rename(columns={'Code  e-Ticket': 'Ticket'}, inplace=True)

In [41]:
sirena_tickets = []
for i in range(len(sirenaExport)):
    sirena_tickets.append(sirenaExport['Ticket'][i])

In [44]:
sirena_ticket = pd.DataFrame(sirena_tickets)
dup = sirena_ticket.duplicated(keep=False)

In [45]:
dup.sum()

0